import type { User, Role, Permission, KPIMetric } from "@/types";

// ─── Permissions ────────────────────────────────────
export const mockPermissions: Permission[] = [
  {
    id: "p1",
    name: "user.create",
    description: "Create new users",
    module: "Users",
    action: "create",
  },
  { id: "p2", name: "user.read", description: "View users", module: "Users", action: "read" },
  { id: "p3", name: "user.update", description: "Edit users", module: "Users", action: "update" },
  { id: "p4", name: "user.delete", description: "Delete users", module: "Users", action: "delete" },
  { id: "p5", name: "role.create", description: "Create roles", module: "Roles", action: "create" },
  { id: "p6", name: "role.read", description: "View roles", module: "Roles", action: "read" },
  { id: "p7", name: "role.update", description: "Edit roles", module: "Roles", action: "update" },
  { id: "p8", name: "role.delete", description: "Delete roles", module: "Roles", action: "delete" },
  {
    id: "p9",
    name: "permission.read",
    description: "View permissions",
    module: "Permissions",
    action: "read",
  },
  {
    id: "p10",
    name: "permission.update",
    description: "Edit permissions",
    module: "Permissions",
    action: "update",
  },
  {
    id: "p11",
    name: "dashboard.read",
    description: "View dashboard",
    module: "Dashboard",
    action: "read",
  },
  {
    id: "p12",
    name: "settings.update",
    description: "Manage settings",
    module: "Settings",
    action: "update",
  },
];

// ─── Roles ──────────────────────────────────────────
export const mockRoles: Role[] = [
  {
    id: "r1",
    name: "Super Admin",
    description: "Full system access with all permissions",
    permissions: mockPermissions,
    userCount: 2,
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "r2",
    name: "Admin",
    description: "Administrative access without permission management",
    permissions: mockPermissions.filter((p) => !p.name.startsWith("permission")),
    userCount: 5,
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "r3",
    name: "Editor",
    description: "Can view and edit content",
    permissions: mockPermissions.filter((p) => p.action === "read" || p.action === "update"),
    userCount: 12,
    createdAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "r4",
    name: "Viewer",
    description: "Read-only access to the system",
    permissions: mockPermissions.filter((p) => p.action === "read"),
    userCount: 25,
    createdAt: "2025-03-15T10:00:00Z",
  },
];

// ─── Users ──────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    role: mockRoles[0],
    status: "active",
    createdAt: "2025-01-20T08:30:00Z",
    updatedAt: "2026-04-20T14:00:00Z",
  },
  {
    id: "u2",
    name: "James Rodriguez",
    email: "james.r@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    role: mockRoles[1],
    status: "active",
    createdAt: "2025-02-15T09:00:00Z",
    updatedAt: "2026-04-18T10:00:00Z",
  },
  {
    id: "u3",
    name: "Emily Watson",
    email: "emily.w@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    role: mockRoles[2],
    status: "active",
    createdAt: "2025-03-10T11:00:00Z",
    updatedAt: "2026-04-15T16:00:00Z",
  },
  {
    id: "u4",
    name: "Michael Park",
    email: "michael.p@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    role: mockRoles[2],
    status: "inactive",
    createdAt: "2025-04-05T13:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "u5",
    name: "Lisa Thompson",
    email: "lisa.t@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    role: mockRoles[3],
    status: "active",
    createdAt: "2025-05-12T14:30:00Z",
    updatedAt: "2026-04-22T11:00:00Z",
  },
  {
    id: "u6",
    name: "David Kim",
    email: "david.k@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    role: mockRoles[1],
    status: "active",
    createdAt: "2025-06-08T10:00:00Z",
    updatedAt: "2026-04-21T15:00:00Z",
  },
  {
    id: "u7",
    name: "Anna Petrov",
    email: "anna.p@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anna",
    role: mockRoles[3],
    status: "suspended",
    createdAt: "2025-07-22T09:00:00Z",
    updatedAt: "2026-02-10T12:00:00Z",
  },
  {
    id: "u8",
    name: "Robert Chang",
    email: "robert.c@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    role: mockRoles[2],
    status: "active",
    createdAt: "2025-08-14T16:00:00Z",
    updatedAt: "2026-04-19T13:00:00Z",
  },
  {
    id: "u9",
    name: "Maria Garcia",
    email: "maria.g@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    role: mockRoles[3],
    status: "active",
    createdAt: "2025-09-03T08:00:00Z",
    updatedAt: "2026-04-17T10:00:00Z",
  },
  {
    id: "u10",
    name: "Alex Turner",
    email: "alex.t@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    role: mockRoles[1],
    status: "active",
    createdAt: "2025-10-18T11:00:00Z",
    updatedAt: "2026-04-23T09:00:00Z",
  },
];

// ─── KPI Metrics ────────────────────────────────────
export const mockKPIMetrics: KPIMetric[] = [
  {
    id: "kpi1",
    title: "Total Users",
    value: 2847,
    change: 12.5,
    changeType: "increase",
    icon: "users",
  },
  {
    id: "kpi2",
    title: "Active Sessions",
    value: 1423,
    change: 8.2,
    changeType: "increase",
    icon: "activity",
  },
  { id: "kpi3", title: "Total Roles", value: 4, change: 0, changeType: "increase", icon: "shield" },
  { id: "kpi4", title: "Permissions", value: 12, change: 2.1, changeType: "increase", icon: "key" },
];

// ─── Chart data ─────────────────────────────────────
export const mockChartData = [
  { name: "Jan", users: 400, sessions: 240 },
  { name: "Feb", users: 530, sessions: 339 },
  { name: "Mar", users: 720, sessions: 480 },
  { name: "Apr", users: 890, sessions: 580 },
  { name: "May", users: 1100, sessions: 690 },
  { name: "Jun", users: 1350, sessions: 850 },
  { name: "Jul", users: 1600, sessions: 980 },
  { name: "Aug", users: 1890, sessions: 1100 },
  { name: "Sep", users: 2100, sessions: 1250 },
  { name: "Oct", users: 2400, sessions: 1350 },
  { name: "Nov", users: 2650, sessions: 1400 },
  { name: "Dec", users: 2847, sessions: 1423 },
];

export const mockActivityData = [
  { name: "Mon", value: 120 },
  { name: "Tue", value: 180 },
  { name: "Wed", value: 150 },
  { name: "Thu", value: 210 },
  { name: "Fri", value: 190 },
  { name: "Sat", value: 80 },
  { name: "Sun", value: 60 },
];
