/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        /* ── shadcn/ui base (HSL triplet system) ── */
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        /* ── Figma design tokens (hex/rgba values) ── */
        general: {
          background: "var(--general-background)",
          foreground: "var(--general-foreground)",
          primary: "var(--general-primary)",
          "primary-foreground": "var(--general-primary-foreground)",
          secondary: "var(--general-secondary)",
          "secondary-foreground": "var(--general-secondary-foreground)",
          muted: "var(--general-muted)",
          "muted-foreground": "var(--general-muted-foreground)",
          accent: "var(--general-accent)",
          "accent-foreground": "var(--general-accent-foreground)",
          destructive: "var(--general-destructive)",
          "destructive-foreground": "var(--general-destructive-foreground)",
          border: "var(--general-border)",
          input: "var(--general-input)",
          "mute-input": "var(--general-mute-input)",
          "page-bg": "var(--general-page-bg)",
          "table-striped": "var(--general-table-striped-background)",
        },
        focus: {
          ring: "var(--focus-ring)",
          "ring-error": "var(--focus-ring-error)",
          "ring-primary": "var(--focus-ring-primary)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
          muted: "var(--sidebar-unofficial-sidebar-muted)",
        },
        unofficial: {
          "border-0": "var(--unofficial-border-0)",
          "border-1": "var(--unofficial-border-1)",
          "border-3": "var(--unofficial-border-3)",
          "border-4": "var(--unofficial-border-4)",
          "border-5": "var(--unofficial-border-5)",
          "border-primary": "var(--unofficial-border-primary)",
          "accent-0": "var(--unofficial-accent-0)",
          "accent-2": "var(--unofficial-accent-2)",
          "accent-3": "var(--unofficial-accent-3)",
          "primary-hover": "var(--unofficial-primary-hover)",
          "secondary-hover": "var(--unofficial-secondary-hover)",
          "mid-alt": "var(--unofficial-mid-alt)",
          "ghost-hover": "var(--unofficial-ghost-hover)",
          "ghost-foreground": "var(--unofficial-ghost-foreground)",
          ghost: "var(--unofficial-ghost)",
          "destructive-subtle": "var(--unofficial-destructive-subtle)",
          "destructive-border": "var(--unofficial-destructive-border)",
          "destructive-text": "var(--unofficial-destructive-text)",
          backdrop: "var(--unofficial-backdrop)",
          outline: "var(--unofficial-outline)",
          "outline-hover": "var(--unofficial-outline-hover)",
          "outline-active": "var(--unofficial-outline-active)",
          "foreground-alt": "var(--unofficial-foreground-alt)",
          "body-background": "var(--unofficial-body-background)",
          breadcrumb: "var(--unofficial-breadcrumb)",
          "data-foreground": "var(--unofficial-data-foreground)",
        },
        badge: {
          positive: "var(--badge-positive)",
          negative: "var(--badge-negative)",
          warning: "var(--badge-warning)",
          info: "var(--badge-info)",
        },
        semantic: {
          success: "var(--semantic-success)",
          "success-border": "var(--semantic-success-border)",
          "success-foreground": "var(--semantic-success-foreground)",
          error: "var(--semantic-error)",
          "error-border": "var(--semantic-error-border)",
          "error-foreground": "var(--semantic-error-foreground)",
          warning: "var(--semantic-warning)",
          "warning-border": "var(--semantic-warning-border)",
          "warning-foreground": "var(--semantic-warning-foreground)",
          info: "var(--semantic-info)",
          "info-border": "var(--semantic-info-border)",
          "info-foreground": "var(--semantic-info-foreground)",
        },
        chart: {
          1: "var(--chart-chart-1)",
          2: "var(--chart-chart-2)",
          3: "var(--chart-chart-3)",
          4: "var(--chart-chart-4)",
          5: "var(--chart-chart-5)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
